apiVersion: v1
kind: Namespace
metadata:
  name: pop
---
apiVersion: v1
kind: Secret
metadata:
  namespace: pop
  name: postgres-secrets
stringData:
  password: super-secret
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: pop
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: prefect
            - name: POSTGRES_USER
              value: prefect
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          ports:
            - containerPort: 5432
          # volumeMounts:
          #   - name: postgres-database
          #     mountPath: /var/lib/postgresql/data/
          #     subPath: postgres
  # volumeClaimTemplates:
  #   - metadata:
  #       name: postgres-database
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       storageClassName: rook-block
  #       resources:
  #         requests:
  #           storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: pop
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: prefect.io/v3
kind: PrefectServer
metadata:
  namespace: pop
  name: my-server
spec:
  postgres:
    host: postgres
    port: 5432
    user: prefect
    passwordSecretKeyRef:
      name: postgres-secrets
      key: password
    database: prefect
  settings:
    - name: PREFECT_LOGGING_SERVER_LEVEL
      value: INFO
    - name: PREFECT_SERVER_ANALYTICS_ENABLED
      value: "false"
---
apiVersion: prefect.io/v3
kind: PrefectWorkPool
metadata:
  namespace: pop
  name: my-work-pool
spec:
  server:
    namespace: pop
    name: my-server
  workers: 2
