apiVersion: v1
kind: Secret
metadata:
  namespace: pop-pg
  name: postgres-secrets
stringData:
  password: super-secret
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: pop-pg
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: prefect
            - name: POSTGRES_USER
              value: prefect
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-database
              mountPath: /var/lib/postgresql/data/
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-database
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: pop-pg
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
